ALTER SESSION SET CONTAINER = FAMILHASPDB;

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER KEYCLOAK IDENTIFIED BY keycloak123';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -01920 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO KEYCLOAK';
  EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO KEYCLOAK';
  EXECUTE IMMEDIATE 'GRANT SELECT ON SYS.DBA_RECYCLEBIN TO KEYCLOAK';
  EXECUTE IMMEDIATE 'ALTER USER KEYCLOAK DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
END;
/
